[package]
name = "hc-gtk"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gtk = { version = "0.4.8", package = "gtk4", features = ["v4_8"]}

form_selector = { path = "../form_selector" }
#hoplite_verbs_rs = { path = "../hoplite_verbs_rs" }
#polytonic-greek = { path = "../polytonic-greek" }

#form_selector = { git = "https://github.com/jeremymarch/form_selector", version = "0.3.0" }
hoplite_verbs_rs = { git = "https://github.com/jeremymarch/hoplite_verbs_rs", version = "0.3.2" }
polytonic-greek = { git = "https://github.com/jeremymarch/polytonic-greek", version = "0.3.2" }

adw = { version = "0.1.1", package = "libadwaita" }
